### ISSUE TITLE
Missing icons?

### ISSUE THREAD

**Issue by ericp1337** [responsiv/flat-theme#1]
So, I went on to the Flat UI homepage to look up some of the icon codes for the theme and noticed that some of them don't seem to work. Some of the ones I noticed not working are github & wordpress, there are also probably many more that aren't available.

I was wondering if I have to include them some how or if I am just not using them correctly. I assumed the div class would be the same as the flat UI official.

**Comment by LukeTowers** [comment]
The theme has now been updated to utilize the latest versions of its dependancies, those icon codes should work now. Also, Font Awesome 4.7.0 is now being used so feel free to use any of those icons as well. 

@daftspunk this can be closed now
