### ISSUE TITLE
Less don't catch nested imports modifications

### ISSUE THREAD

**Issue by Adrion** [responsiv/flat-theme#11]
Hi,
First thanks for this useful starter template :)

I have some less compiling issues with the template. 
I started by set : `'enableAssetDeepHashing' => true,`
But it doesn't catch any modifications in nested imports (like `theme/variables.less`).
I think it's the same limitation: https://github.com/octobercms/october/issues/2345

A workaround is to remove `theme/all.less` and add its content into `theme.less`
This way I remove one nesting level.

Do you have a better/cleaner solution ? I don't found anything in October forums or documentation.
If not do you want a simple PR for this ?

Thanks !

**Comment by daftspunk** [comment]
Sure, a PR for this would be accepted.
