### ISSUE TITLE
Sublinks in nav partial

### ISSUE THREAD

**Issue by richardtorres314** [responsiv/flat-theme#15]
The sublinks do not seem to render for October CMS Build 434. Any idea why that my be? Thank you!

**Comment by DTseven** [comment]
Got the same problem on 434. All Dropdown-Nav-Menus open but none shows any content!

**Comment by osbre** [comment]
me too have this problem

**Comment by osbre** [comment]
wow, it have solution:
https://github.com/responsiv/flat-theme/pull/14
