### ISSUE TITLE
How can I protect sublinks nav partial? Based on if User is logged in?

### ISSUE THREAD

**Issue by AxDSan** [responsiv/flat-theme#18]
Hello, I would like to make a specific link, namely `user`, with its sublinks, unavailable to guest users... so it won't display this link, but display it as soon as the guest registers or sign in to the website.

```
{% set
    links = {
        'home': ['home', 'Home'],
        'discord': ['discord', 'Discord'],
        'team': ['team', 'Team'],
        'user': {
            name: user.username,
            sublinks: {
                'dashboard': ['user/dashboard', 'Dashboard'],
                'logout': ['user/logout', 'Logout']
            },
        }
    }
%}
```

How can I do this with this template?

**Comment by AxDSan** [comment]
I did this:


```
{%if user %}
{% set
    links = {
        'home': ['home', 'Home'],
        'discord': ['discord', 'Discord'],
        'team': ['team', 'Team'],
        'user': {
            name: user.username,
            sublinks: {
                'dashboard': ['user/dashboard', 'Dashboard'],
                'logout': ['user/logout', 'Logout']
            },
        }
    }
%}
{% else %}
{% set
    links = {
        'home': ['home', 'Home'],
        'discord': ['discord', 'Discord'],
        'team': ['team', 'Team']
    }
%}
{%endif%}
```

if anyone comes up with a better idea, let me know, its late in the night, i... need...sleep...

**Comment by LukeTowers** [comment]
@AxDSan if you wanted to manage both menus via the RainLab.Pages plugin you could also include the menu component on the page / layout twice each referencing a different menu and then conditionally choose which one to display via your `{% if user %}` conditional block.
