### ISSUE TITLE
Outdated Dependencies

### ISSUE THREAD

**Issue by LukeTowers** [responsiv/flat-theme#4]
This theme hasn't been updated in quite a while and as such it's dependencies are pretty out of date. The most notable one is Font Awesome, being 3.2.1 and the current version being 4.7.0; however almost all of the other dependencies are just as out of date.

@daftspunk, would you accept a pull request bring this theme's dependencies up to date and integrating with October's LESS compiler instead of relying on pre compilation?

**Comment by daftspunk** [comment]
Sure thing
