### ISSUE TITLE
UI interface has strange sidebar

### ISSUE THREAD

**Issue by roulendz** [responsiv/flat-theme#8]
https://failiem.lv/u/5gqxdg6z

Here are images from my phone using Chrome. 

It is really strange.

**Comment by daftspunk** [comment]
![screenshot_20170330-081515](https://cloud.githubusercontent.com/assets/1392869/24490250/780e5a9a-156d-11e7-97b6-87c98f77eca2.png)
![screenshot_20170330-081441](https://cloud.githubusercontent.com/assets/1392869/24490251/780eaed2-156d-11e7-9ce6-7ce176be4ad9.png)

**Comment by Adrion** [comment]
```
.swatches-col {
            width: 800px;
            margin-left: -5px;
}
```
<img width="662" alt="capture d ecran 2017-06-01 a 14 17 50" src="https://cloud.githubusercontent.com/assets/5418815/26679401/27f852ce-46d5-11e7-8bcd-323f12dae5ab.png">

pallete table is too large. but it's not the only element.
I'll see to make a PR and make it responsive.
