### ISSUE TITLE
Unsecured contents

### ISSUE THREAD

**Issue by AdrienAdB** [responsiv/flat-theme#9]
Hi,
My OctoberCMS instance is hosted on a secured connection.
Firefox isn't opening some unsecured contents in pages "Demonstration" and ui-elements".
Issues has been solved by modifying "http" by "https" on below pages:

demonstration page:

31 `<iframe src="https://player.vimeo.com/video/29568236?color=3498db" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

ui-elements page:

408 `<source src="https://iurevych.github.com/Flat-UI-videos/big_buck_bunny.mp4" type="video/mp4">`
409 `<source src="https://iurevych.github.com/Flat-UI-videos/big_buck_bunny.webm" type="video/webm">`

**Comment by daftspunk** [comment]
Thanks! Feel free to submit a PR that fixes this.

**Comment by osbre** [comment]
for this: https://github.com/responsiv/flat-theme/pull/10
